### ISSUE TITLE
ATM tasks

### ISSUE THREAD

**Issue by RuthLess1303** [RuthLess1303/BankingSystem#22]
**Task List**

- [x] Check Endpoint functionality
- [x] Check Repositories' functionality
- [x] Manually test functions which are using repositories
- [x] Write Unit Tests for validation(s) which are not using repositories
