### ISSUE TITLE
Reporting Tasks

### ISSUE THREAD

**Issue by RuthLess1303** [RuthLess1303/BankingSystem#23]
**Task List**

- [x] Move Repositories from shared Db to Reporting Core (ones which are used in reporting itself)
- [x] Check Endpoint functionality
- [x] Check Repositories' functionality
- [x] Manually test functions which are using repositories
- [x] Write Unit Tests for validation(s) which are not using repositories
