### ISSUE TITLE
Async checks

### ISSUE THREAD

**Issue by RuthLess1303** [RuthLess1303/BankingSystem#24]
**Description**
This task should be done on all the projects: _ATM_, _Internet Bank_, _Reporting System_, _Banking System Db_

**Task List**

- [x] Check all files in ATM project
- [x] Fix non async function(s)
- [x] Find where functions were used and add "await" in the front
- [x] Check all files in Internet Bank project
- [x] Fix non async function(s)
- [x] Find where functions were used and add "await" in the front
- [x] Check all files in Reporting System project
- [x] Fix non async function(s)
- [x] Find where functions were used and add "await" in the front
- [x] Check all files in Banking System Db project
- [x] Fix non async function(s)
- [x] Find where functions were used and add "await" in the front
