### ISSUE TITLE
Regression Testing

### ISSUE THREAD

**Issue by RuthLess1303** [RuthLess1303/BankingSystem#25]
**_Description_**

Regression Testing means to test everything in the project.
_It should be made after all the issue tasks are completed !!!_

**Task List**

- [ ] Internet Bank API
- [ ] Internet Bank Core
- [ ] Banking System Shared Db
- [ ] Reporting API
- [ ] Reporting Core
- [ ] ATM API
- [ ] ATM Core
